### PR TITLE
Add prerelease for builds

### PR DESCRIPTION
**Pull request by LeoDog896**
This adds a prerelease for vala for any platform that doesnt already have the repository

### CODE REVIEW

**Comment by Prince781** [comment]
I don't see the need for prereleases in this project because we never distribute a binary in our releases, so users can always just clone the repo and build. Is there a need for prereleases on your part?

**Comment by LeoDog896** [comment]
> I don't see the need for prereleases in this project because we never distribute a binary in our releases, so users can always just clone the repo and build. Is there a need for prereleases on your part?

It actually wasn't for me, but rather for my friend who was using gitpod and had trouble understanding how to build it -- if there's a different way the releases are bundled let me know. I did think itll be useful for any distributions that arent supported yet with a quick setup -- i was also considering making a install.sh file in some folder and making a small install script, like https://deno.land's install script

**Comment by LeoDog896** [comment]
@Prince781 are you still there?

**Comment by Prince781** [comment]
@LeoDog896 yeah. I was too busy to evaluate this then, but I should be able to take a look soon.

**Comment by Prince781** [comment]
I think I can raise objections to this in a few ways:

1. VLS is released as a source tarball here along with packages for your favorite distro on OBS/etc. If you have the `meson` build system and the dependencies, this is easy to build. All you do is `git clone` and `meson build`. Therefore this seems unnecessary for the purpose of making VLS more available.
2. Pre-releases aren't something I can vouch for, and I don't want to encourage people to use software that might have bugs. I make sure that there are no regressions before each release, and I wouldn't be able to do this with pre-releases. If people want to use VLS from master, they'll have to clone and build it themselves.
3. Can these pre-releases be built for any architecture, not just x86_64? Maybe it's possible if you install a cross-compiler.
4. I don't want to rely too heavily on GitHub actions for this project.

**Comment by Prince781** [comment]
I'm going to close this, but it's possible I may change my mind and reopen it.

**Pull request closed without merging**
