### PR TITLE
add pause for debugger attachment in test-client

### PR DESCRIPTION
**Pull request by benwaffle**
- testclient: add pause for debugger feature
- Fix gir errors when meson fails

### CODE REVIEW

**Comment by Prince781** [comment]
Does this fix the crash in bug #259 ?

**Comment by benwaffle** [comment]
No, can't reproduce that yet.

**Comment by Prince781** [comment]
Why `actions/checkout@v3`? Also, could you place that change in a separate PR? Otherwise this looks good to me.

**Review by Prince781 — CHANGES_REQUESTED** [review]
Please move the workflow update to a separate PR.

**Comment by benwaffle** [comment]
cherry-picked into master

**Pull request closed without merging**
